-- In-app notifications generated by operational events.

create or replace function public.notify_document_submitted()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.notifications (user_id, title, body, link)
  select ur.user_id, 'Documento enviado', a.full_name || ' enviou ' || new.title,
    '/admin/documents'
  from public.user_roles ur
  join public.athletes a on a.id = new.athlete_id
  where ur.role = 'agency_admin';
  return new;
end $$;

drop trigger if exists documents_notify_submitted on public.documents;
create trigger documents_notify_submitted
  after insert on public.documents
  for each row execute function public.notify_document_submitted();

create or replace function public.sync_checklist_from_document()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.checklist_item_id is not null then
    update public.athlete_checklist_items
    set document_id = new.id, status = new.status
    where athlete_id = new.athlete_id
      and checklist_item_id = new.checklist_item_id;
  end if;
  return new;
end $$;

drop trigger if exists documents_sync_checklist_insert on public.documents;
create trigger documents_sync_checklist_insert
  after insert on public.documents
  for each row execute function public.sync_checklist_from_document();

create or replace function public.sync_checklist_review()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.checklist_item_id is not null and old.status is distinct from new.status then
    update public.athlete_checklist_items
    set status = new.status,
        completed_at = case when new.status = 'approved' then now() else null end
    where athlete_id = new.athlete_id
      and checklist_item_id = new.checklist_item_id;
  end if;
  return new;
end $$;

drop trigger if exists documents_sync_checklist_update on public.documents;
create trigger documents_sync_checklist_update
  after update on public.documents
  for each row execute function public.sync_checklist_review();

create or replace function public.notify_document_reviewed()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if old.status is distinct from new.status and new.status in ('approved','rejected','resubmit') then
    insert into public.notifications (user_id, title, body, link)
    select a.user_id,
      case new.status
        when 'approved' then 'Documento aprovado'
        when 'resubmit' then 'Novo envio solicitado'
        else 'Documento reprovado'
      end,
      new.title || coalesce(': ' || new.review_notes, ''),
      '/portal/documents'
    from public.athletes a
    where a.id = new.athlete_id and a.user_id is not null;
  end if;
  return new;
end $$;

drop trigger if exists documents_notify_reviewed on public.documents;
create trigger documents_notify_reviewed
  after update on public.documents
  for each row execute function public.notify_document_reviewed();

create or replace function public.notify_stage_changed()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if old.status is distinct from new.status then
    insert into public.notifications (user_id, title, body, link)
    select a.user_id, 'Pipeline atualizado',
      coalesce(ps.name_pt, ps.name_en) || ': ' || new.status::text,
      '/portal/pipeline'
    from public.athletes a
    join public.pipeline_stages ps on ps.id = new.stage_id
    where a.id = new.athlete_id and a.user_id is not null;
  end if;
  return new;
end $$;

drop trigger if exists progress_notify_changed on public.athlete_stage_progress;
create trigger progress_notify_changed
  after update on public.athlete_stage_progress
  for each row execute function public.notify_stage_changed();

-- Athlete uploads stay in a private bucket until an agency administrator approves them.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'athlete-media-pending',
  'athlete-media-pending',
  false,
  524288000,
  array['image/jpeg','image/png','image/webp','video/mp4','video/quicktime']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists pending_media_select on storage.objects;
create policy pending_media_select on storage.objects for select to authenticated
  using (
    bucket_id = 'athlete-media-pending'
    and (
      public.is_agency_admin()
      or public.owns_athlete((storage.foldername(name))[1]::uuid)
    )
  );

drop policy if exists pending_media_insert on storage.objects;
create policy pending_media_insert on storage.objects for insert to authenticated
  with check (
    bucket_id = 'athlete-media-pending'
    and public.owns_athlete((storage.foldername(name))[1]::uuid)
  );

drop policy if exists pending_media_delete on storage.objects;
create policy pending_media_delete on storage.objects for delete to authenticated
  using (bucket_id = 'athlete-media-pending' and public.is_agency_admin());

drop policy if exists media_auth_write on storage.objects;
create policy media_auth_write on storage.objects for insert to authenticated
  with check (
    bucket_id = 'athlete-media'
    and (
      public.is_agency_admin()
      or public.owns_athlete((storage.foldername(name))[1]::uuid)
    )
  );
