-- Migration: Lista completa de países ISO 3166-1 com códigos, nomes em inglês e português, e bandeiras emoji.
-- Idempotente com ON CONFLICT (code) DO UPDATE.

insert into public.countries (code, name_en, name_pt, flag_emoji) values
  ('AF', 'Afghanistan', 'Afeganistão', '🇦🇫'),
  ('AL', 'Albania', 'Albânia', '🇦🇱'),
  ('DZ', 'Algeria', 'Argélia', '🇩🇿'),
  ('AD', 'Andorra', 'Andorra', '🇦🇩'),
  ('AO', 'Angola', 'Angola', '🇦🇴'),
  ('AG', 'Antigua and Barbuda', 'Antígua e Barbuda', '🇦🇬'),
  ('AR', 'Argentina', 'Argentina', '🇦🇷'),
  ('AM', 'Armenia', 'Armênia', '🇦🇲'),
  ('AU', 'Australia', 'Austrália', '🇦🇺'),
  ('AT', 'Austria', 'Áustria', '🇦🇹'),
  ('AZ', 'Azerbaijan', 'Azerbaijão', '🇦🇿'),
  ('BS', 'Bahamas', 'Bahamas', '🇧🇸'),
  ('BH', 'Bahrain', 'Bahrein', '🇧🇭'),
  ('BD', 'Bangladesh', 'Bangladesh', '🇧🇩'),
  ('BB', 'Barbados', 'Barbados', '🇧🇧'),
  ('BY', 'Belarus', 'Bielorrússia', '🇧🇾'),
  ('BE', 'Belgium', 'Bélgica', '🇧🇪'),
  ('BZ', 'Belize', 'Belize', '🇧🇿'),
  ('BJ', 'Benin', 'Benin', '🇧🇯'),
  ('BT', 'Bhutan', 'Butão', '🇧🇹'),
  ('BO', 'Bolivia', 'Bolívia', '🇧🇴'),
  ('BA', 'Bosnia and Herzegovina', 'Bósnia e Herzegovina', '🇧🇦'),
  ('BW', 'Botswana', 'Botsuana', '🇧🇼'),
  ('BR', 'Brazil', 'Brasil', '🇧🇷'),
  ('BN', 'Brunei', 'Brunei', '🇧🇳'),
  ('BG', 'Bulgaria', 'Bulgária', '🇧🇬'),
  ('BF', 'Burkina Faso', 'Burkina Faso', '🇧🇫'),
  ('BI', 'Burundi', 'Burundi', '🇧🇮'),
  ('CV', 'Cabo Verde', 'Cabo Verde', '🇨🇻'),
  ('KH', 'Cambodia', 'Camboja', '🇰🇭'),
  ('CM', 'Cameroon', 'Camarões', '🇨🇲'),
  ('CA', 'Canada', 'Canadá', '🇨🇦'),
  ('CF', 'Central African Republic', 'República Centro-Africana', '🇨🇫'),
  ('TD', 'Chad', 'Chade', '🇹🇩'),
  ('CL', 'Chile', 'Chile', '🇨🇱'),
  ('CN', 'China', 'China', '🇨🇳'),
  ('CO', 'Colombia', 'Colômbia', '🇨🇴'),
  ('KM', 'Comoros', 'Comores', '🇰🇲'),
  ('CG', 'Congo', 'Congo', '🇨🇬'),
  ('CD', 'DR Congo', 'República Democrática do Congo', '🇨🇩'),
  ('CR', 'Costa Rica', 'Costa Rica', '🇨🇷'),
  ('CI', 'Côte d''Ivoire', 'Costa do Marfim', '🇨🇮'),
  ('HR', 'Croatia', 'Croácia', '🇭🇷'),
  ('CU', 'Cuba', 'Cuba', '🇨🇺'),
  ('CY', 'Cyprus', 'Chipre', '🇨🇾'),
  ('CZ', 'Czech Republic', 'República Tcheca', '🇨🇿'),
  ('DK', 'Denmark', 'Dinamarca', '🇩🇰'),
  ('DJ', 'Djibouti', 'Djibuti', '🇩🇯'),
  ('DM', 'Dominica', 'Dominica', '🇩🇲'),
  ('DO', 'Dominican Republic', 'República Dominicana', '🇩🇴'),
  ('EC', 'Ecuador', 'Equador', '🇪🇨'),
  ('EG', 'Egypt', 'Egito', '🇪🇬'),
  ('SV', 'El Salvador', 'El Salvador', '🇸🇻'),
  ('GQ', 'Equatorial Guinea', 'Guiné Equatorial', '🇬🇶'),
  ('ER', 'Eritrea', 'Eritreia', '🇪🇷'),
  ('EE', 'Estonia', 'Estônia', '🇪🇪'),
  ('SZ', 'Eswatini', 'Essuatíni', '🇸🇿'),
  ('ET', 'Ethiopia', 'Etiópia', '🇪🇹'),
  ('FJ', 'Fiji', 'Fiji', '🇫🇯'),
  ('FI', 'Finland', 'Finlândia', '🇫🇮'),
  ('FR', 'France', 'França', '🇫🇷'),
  ('GA', 'Gabon', 'Gabão', '🇬🇦'),
  ('GM', 'Gambia', 'Gâmbia', '🇬🇲'),
  ('GE', 'Georgia', 'Geórgia', '🇬🇪'),
  ('DE', 'Germany', 'Alemanha', '🇩🇪'),
  ('GH', 'Ghana', 'Gana', '🇬🇭'),
  ('GR', 'Greece', 'Grécia', '🇬🇷'),
  ('GD', 'Grenada', 'Granada', '🇬🇩'),
  ('GT', 'Guatemala', 'Guatemala', '🇬🇹'),
  ('GN', 'Guinea', 'Guiné', '🇬🇳'),
  ('GW', 'Guinea-Bissau', 'Guiné-Bissau', '🇬🇼'),
  ('GY', 'Guyana', 'Guiana', '🇬🇾'),
  ('HT', 'Haiti', 'Haiti', '🇭🇹'),
  ('HN', 'Honduras', 'Honduras', '🇭🇳'),
  ('HU', 'Hungary', 'Hungria', '🇭🇺'),
  ('IS', 'Iceland', 'Islândia', '🇮🇸'),
  ('IN', 'India', 'Índia', '🇮🇳'),
  ('ID', 'Indonesia', 'Indonésia', '🇮🇩'),
  ('IR', 'Iran', 'Irã', '🇮🇷'),
  ('IQ', 'Iraq', 'Iraque', '🇮🇶'),
  ('IE', 'Ireland', 'Irlanda', '🇮🇪'),
  ('IL', 'Israel', 'Israel', '🇮🇱'),
  ('IT', 'Italy', 'Itália', '🇮🇹'),
  ('JM', 'Jamaica', 'Jamaica', '🇯🇲'),
  ('JP', 'Japan', 'Japão', '🇯🇵'),
  ('JO', 'Jordan', 'Jordânia', '🇯🇴'),
  ('KZ', 'Kazakhstan', 'Cazaquistão', '🇰🇿'),
  ('KE', 'Kenya', 'Quênia', '🇰🇪'),
  ('KI', 'Kiribati', 'Quiribati', '🇰🇮'),
  ('KP', 'North Korea', 'Coreia do Norte', '🇰🇵'),
  ('KR', 'South Korea', 'Coreia do Sul', '🇰🇷'),
  ('KW', 'Kuwait', 'Kuwait', '🇰🇼'),
  ('KG', 'Kyrgyzstan', 'Quirguistão', '🇰🇬'),
  ('LA', 'Laos', 'Laos', '🇱🇦'),
  ('LV', 'Latvia', 'Letônia', '🇱🇻'),
  ('LB', 'Lebanon', 'Líbano', '🇱🇧'),
  ('LS', 'Lesotho', 'Lesoto', '🇱🇸'),
  ('LR', 'Liberia', 'Libéria', '🇱🇷'),
  ('LY', 'Libya', 'Líbia', '🇱🇾'),
  ('LI', 'Liechtenstein', 'Liechtenstein', '🇱🇮'),
  ('LT', 'Lithuania', 'Lituânia', '🇱🇹'),
  ('LU', 'Luxembourg', 'Luxemburgo', '🇱🇺'),
  ('MG', 'Madagascar', 'Madagascar', '🇲🇬'),
  ('MW', 'Malawi', 'Malawi', '🇲🇼'),
  ('MY', 'Malaysia', 'Malásia', '🇲🇾'),
  ('MV', 'Maldives', 'Maldivas', '🇲🇻'),
  ('ML', 'Mali', 'Mali', '🇲🇱'),
  ('MT', 'Malta', 'Malta', '🇲🇹'),
  ('MH', 'Marshall Islands', 'Ilhas Marshall', '🇲🇭'),
  ('MR', 'Mauritania', 'Mauritânia', '🇲🇷'),
  ('MU', 'Mauritius', 'Maurício', '🇲🇺'),
  ('MX', 'Mexico', 'México', '🇲🇽'),
  ('FM', 'Micronesia', 'Micronésia', '🇫🇲'),
  ('MD', 'Moldova', 'Moldávia', '🇲🇩'),
  ('MC', 'Monaco', 'Mônaco', '🇲🇨'),
  ('MN', 'Mongolia', 'Mongólia', '🇲🇳'),
  ('ME', 'Montenegro', 'Montenegro', '🇲🇪'),
  ('MA', 'Morocco', 'Marrocos', '🇲🇦'),
  ('MZ', 'Mozambique', 'Moçambique', '🇲🇿'),
  ('MM', 'Myanmar', 'Mianmar', '🇲🇲'),
  ('NA', 'Namibia', 'Namíbia', '🇳🇦'),
  ('NR', 'Nauru', 'Nauru', '🇳🇷'),
  ('NP', 'Nepal', 'Nepal', '🇳🇵'),
  ('NL', 'Netherlands', 'Países Baixos', '🇳🇱'),
  ('NZ', 'New Zealand', 'Nova Zelândia', '🇳🇿'),
  ('NI', 'Nicaragua', 'Nicarágua', '🇳🇮'),
  ('NE', 'Niger', 'Níger', '🇳🇪'),
  ('NG', 'Nigeria', 'Nigéria', '🇳🇬'),
  ('MK', 'North Macedonia', 'Macedônia do Norte', '🇲🇰'),
  ('NO', 'Norway', 'Noruega', '🇳🇴'),
  ('OM', 'Oman', 'Omã', '🇴🇲'),
  ('PK', 'Pakistan', 'Paquistão', '🇵🇰'),
  ('PW', 'Palau', 'Palau', '🇵🇼'),
  ('PS', 'Palestine', 'Palestina', '🇵🇸'),
  ('PA', 'Panama', 'Panamá', '🇵🇦'),
  ('PG', 'Papua New Guinea', 'Papua-Nova Guiné', '🇵🇬'),
  ('PY', 'Paraguay', 'Paraguai', '🇵🇾'),
  ('PE', 'Peru', 'Peru', '🇵🇪'),
  ('PH', 'Philippines', 'Filipinas', '🇵🇭'),
  ('PL', 'Poland', 'Polônia', '🇵🇱'),
  ('PT', 'Portugal', 'Portugal', '🇵🇹'),
  ('QA', 'Qatar', 'Catar', '🇶🇦'),
  ('RO', 'Romania', 'Romênia', '🇷🇴'),
  ('RU', 'Russia', 'Rússia', '🇷🇺'),
  ('RW', 'Rwanda', 'Ruanda', '🇷🇼'),
  ('KN', 'Saint Kitts and Nevis', 'São Cristóvão e Névis', '🇰🇳'),
  ('LC', 'Saint Lucia', 'Santa Lúcia', '🇱🇨'),
  ('VC', 'Saint Vincent and the Grenadines', 'São Vicente e Granadinas', '🇻🇨'),
  ('WS', 'Samoa', 'Samoa', '🇼🇸'),
  ('SM', 'San Marino', 'San Marino', '🇸🇲'),
  ('ST', 'Sao Tome and Principe', 'São Tomé e Príncipe', '🇸🇹'),
  ('SA', 'Saudi Arabia', 'Arábia Saudita', '🇸🇦'),
  ('SN', 'Senegal', 'Senegal', '🇸🇳'),
  ('RS', 'Serbia', 'Sérvia', '🇷🇸'),
  ('SC', 'Seychelles', 'Seicheles', '🇸🇨'),
  ('SL', 'Sierra Leone', 'Serra Leoa', '🇸🇱'),
  ('SG', 'Singapore', 'Cingapura', '🇸🇬'),
  ('SK', 'Slovakia', 'Eslováquia', '🇸🇰'),
  ('SI', 'Slovenia', 'Eslovênia', '🇸🇮'),
  ('SB', 'Solomon Islands', 'Ilhas Salomão', '🇸🇧'),
  ('SO', 'Somalia', 'Somália', '🇸🇴'),
  ('ZA', 'South Africa', 'África do Sul', '🇿🇦'),
  ('SS', 'South Sudan', 'Sudão do Sul', '🇸🇸'),
  ('ES', 'Spain', 'Espanha', '🇪🇸'),
  ('LK', 'Sri Lanka', 'Sri Lanka', '🇱🇰'),
  ('SD', 'Sudan', 'Sudão', '🇸🇩'),
  ('SR', 'Suriname', 'Suriname', '🇸🇷'),
  ('SE', 'Sweden', 'Suécia', '🇸🇪'),
  ('CH', 'Switzerland', 'Suíça', '🇨🇭'),
  ('SY', 'Syria', 'Síria', '🇸🇾'),
  ('TW', 'Taiwan', 'Taiwan', '🇹🇼'),
  ('TJ', 'Tajikistan', 'Tajiquistão', '🇹🇯'),
  ('TZ', 'Tanzania', 'Tanzânia', '🇹🇿'),
  ('TH', 'Thailand', 'Tailândia', '🇹🇭'),
  ('TL', 'Timor-Leste', 'Timor-Leste', '🇹🇱'),
  ('TG', 'Togo', 'Togo', '🇹🇬'),
  ('TO', 'Tonga', 'Tonga', '🇹🇴'),
  ('TT', 'Trinidad and Tobago', 'Trinidad e Tobago', '🇹🇹'),
  ('TN', 'Tunisia', 'Tunísia', '🇹🇳'),
  ('TR', 'Turkey', 'Turquia', '🇹🇷'),
  ('TM', 'Turkmenistan', 'Turcomenistão', '🇹🇲'),
  ('TV', 'Tuvalu', 'Tuvalu', '🇹🇻'),
  ('UG', 'Uganda', 'Uganda', '🇺🇬'),
  ('UA', 'Ukraine', 'Ucrânia', '🇺🇦'),
  ('AE', 'United Arab Emirates', 'Emirados Árabes Unidos', '🇦🇪'),
  ('GB', 'United Kingdom', 'Reino Unido', '🇬🇧'),
  ('US', 'United States', 'Estados Unidos', '🇺🇸'),
  ('UY', 'Uruguay', 'Uruguai', '🇺🇾'),
  ('UZ', 'Uzbekistan', 'Uzbequistão', '🇺🇿'),
  ('VU', 'Vanuatu', 'Vanuatu', '🇻🇺'),
  ('VE', 'Venezuela', 'Venezuela', '🇻🇪'),
  ('VN', 'Vietnam', 'Vietnã', '🇻🇳'),
  ('YE', 'Yemen', 'Iêmen', '🇾🇪'),
  ('ZM', 'Zambia', 'Zâmbia', '🇿🇲'),
  ('ZW', 'Zimbabwe', 'Zimbábue', '🇿🇼')
on conflict (code) do update set
  name_en = excluded.name_en,
  name_pt = excluded.name_pt,
  flag_emoji = excluded.flag_emoji;
