/**
 * Constantes oficiais de marca, tokens visuais e URLs absolutas para e-mails institucionais
 * Baseado no design system e no poster "2027 VOLLEYBALL RECRUITING BOARD".
 */

export const EMAIL_BASE_URL = "https://portfolio.goteamgoagency.com";

export const EMAIL_COLORS = {
  darkGreenDeep: "#032812",
  darkGreenPrimary: "#084323",
  darkGreenHero: "#05301a",
  darkGreenBar: "#08311c",
  goldPrimary: "#f69e00",
  goldLight: "#f0a500",
  cardBg: "#f3f6f1",
  cardBorder: "#e3e9dc",
  ctaBg: "#eef3ec",
  bodyBg: "#f8faf5",
  textDark: "#032812",
  textMuted: "#4b6353",
  white: "#ffffff",
  lineDivider: "#e3e9dc",
  goldLine: "#f69e00",
  badgeGreenBg: "#d4e5d8",
  badgeGreenText: "#084323",
  badgeGoldBg: "#fcedcc",
  badgeGoldBorder: "#f69e00",
  badgeGoldText: "#032812",
  buttonSecondaryBg: "#f3f6f1",
  buttonSecondaryBorder: "#e3e9dc",
  heroSubtitle: "#d2ded6",
  copyrightText: "#8ba092",
} as const;

export const EMAIL_ASSETS = {
  logoUrl: `${EMAIL_BASE_URL}/email/logo-gtg.png`,
  heroBgUrl: `${EMAIL_BASE_URL}/email/hero-email.jpg`,
  handwrittenMoreThanAGame: `${EMAIL_BASE_URL}/email/handwritten-more-than-a-game.png`,
  handwrittenDifferentAthletes: `${EMAIL_BASE_URL}/email/handwritten-different-athletes.png`,
  icons: {
    academic: `${EMAIL_BASE_URL}/email/icons/academic.png`,
    film: `${EMAIL_BASE_URL}/email/icons/film.png`,
    users: `${EMAIL_BASE_URL}/email/icons/users.png`,
    globe: `${EMAIL_BASE_URL}/email/icons/globe.png`,
    height: `${EMAIL_BASE_URL}/email/icons/height.png`,
    gradCap: `${EMAIL_BASE_URL}/email/icons/grad-cap.png`,
    stats: `${EMAIL_BASE_URL}/email/icons/stats.png`,
    star: `${EMAIL_BASE_URL}/email/icons/star.png`,
    dollar: `${EMAIL_BASE_URL}/email/icons/dollar.png`,
    playCircle: `${EMAIL_BASE_URL}/email/icons/play-circle.png`,
    arrowGold: `${EMAIL_BASE_URL}/email/icons/arrow-gold.png`,
    email: `${EMAIL_BASE_URL}/email/icons/email.png`,
    instagram: `${EMAIL_BASE_URL}/email/icons/instagram.png`,
    website: `${EMAIL_BASE_URL}/email/icons/website.png`,
  },
  flagUrl: (code: string) => {
    const clean = (code || "").trim().toLowerCase();
    const supported = ["bra", "usa", "can", "col", "arg", "dom", "pri", "ita", "esp", "deu"];
    if (supported.includes(clean)) {
      return `${EMAIL_BASE_URL}/email/flags/${clean}.png`;
    }
    return `${EMAIL_BASE_URL}/email/flags/default.png`;
  },
} as const;

export const EMAIL_SIGNATURE = {
  name: "Fabiana Andrade",
  role: "Founder | Go Team Go Agency",
  agency: "Go Team Go Agency",
  email: "fabiana@goteamgoagency.com",
  instagram: "@goteamgoagency",
  instagramUrl: "https://instagram.com/goteamgoagency",
  website: "https://www.goteamgoagency.com",
  websiteUrl: "https://www.goteamgoagency.com",
} as const;

/**
 * Tabela estática de conversão ISO 3166-1 alpha-2 para alpha-3.
 * Sem dependência de migration de banco.
 */
export const ALPHA2_TO_ALPHA3: Record<string, string> = {
  AF: "AFG",
  AL: "ALB",
  DZ: "DZA",
  AD: "AND",
  AO: "AGO",
  AG: "ATG",
  AR: "ARG",
  AM: "ARM",
  AU: "AUS",
  AT: "AUT",
  AZ: "AZE",
  BS: "BHS",
  BH: "BHR",
  BD: "BGD",
  BB: "BRB",
  BY: "BLR",
  BE: "BEL",
  BZ: "BLZ",
  BJ: "BEN",
  BT: "BTN",
  BO: "BOL",
  BA: "BIH",
  BW: "BWA",
  BR: "BRA",
  BN: "BRN",
  BG: "BGR",
  BF: "BFA",
  BI: "BDI",
  CV: "CPV",
  KH: "KHM",
  CM: "CMR",
  CA: "CAN",
  CF: "CAF",
  TD: "TCD",
  CL: "CHL",
  CN: "CHN",
  CO: "COL",
  KM: "COM",
  CG: "COG",
  CD: "COD",
  CR: "CRI",
  CI: "CIV",
  HR: "HRV",
  CU: "CUB",
  CY: "CYP",
  CZ: "CZE",
  DK: "DNK",
  DJ: "DJI",
  DM: "DMA",
  DO: "DOM",
  EC: "ECU",
  EG: "EGY",
  SV: "SLV",
  GQ: "GNQ",
  ER: "ERI",
  EE: "EST",
  SZ: "SWZ",
  ET: "ETH",
  FJ: "FJI",
  FI: "FIN",
  FR: "FRA",
  GA: "GAB",
  GM: "GMB",
  GE: "GEO",
  DE: "DEU",
  GH: "GHA",
  GR: "GRC",
  GD: "GRD",
  GT: "GTM",
  GN: "GIN",
  GW: "GNB",
  GY: "GUY",
  HT: "HTI",
  HN: "HND",
  HU: "HUN",
  IS: "ISL",
  IN: "IND",
  ID: "IDN",
  IR: "IRN",
  IQ: "IRQ",
  IE: "IRL",
  IL: "ISR",
  IT: "ITA",
  JM: "JAM",
  JP: "JPN",
  JO: "JOR",
  KZ: "KAZ",
  KE: "KEN",
  KI: "KIR",
  KP: "PRK",
  KR: "KOR",
  KW: "KWT",
  KG: "KGZ",
  LA: "LAO",
  LV: "LVA",
  LB: "LBN",
  LS: "LSO",
  LR: "LBR",
  LY: "LBY",
  LI: "LIE",
  LT: "LTU",
  LU: "LUX",
  MG: "MDG",
  MW: "MWI",
  MY: "MYS",
  MV: "MDV",
  ML: "MLI",
  MT: "MLT",
  MH: "MHL",
  MR: "MRT",
  MU: "MUS",
  MX: "MEX",
  FM: "FSM",
  MD: "MDA",
  MC: "MCO",
  MN: "MNG",
  ME: "MNE",
  MA: "MAR",
  MZ: "MOZ",
  MM: "MMR",
  NA: "NAM",
  NR: "NRU",
  NP: "NPL",
  NL: "NLD",
  NZ: "NZL",
  NI: "NIC",
  NE: "NER",
  NG: "NGA",
  MK: "MKD",
  NO: "NOR",
  OM: "OMN",
  PK: "PAK",
  PW: "PLW",
  PA: "PAN",
  PG: "PNG",
  PY: "PRY",
  PE: "PER",
  PH: "PHL",
  PL: "POL",
  PT: "PRT",
  QA: "QAT",
  RO: "ROU",
  RU: "RUS",
  RW: "RWA",
  KN: "KNA",
  LC: "LCA",
  VC: "VCT",
  WS: "WSM",
  SM: "SMR",
  ST: "STP",
  SA: "SAU",
  SN: "SEN",
  RS: "SRB",
  SC: "SYC",
  SL: "SLE",
  SG: "SGP",
  SK: "SVK",
  SI: "SVN",
  SB: "SLB",
  SO: "SOM",
  ZA: "ZAF",
  SS: "SSD",
  ES: "ESP",
  LK: "LKA",
  SD: "SDN",
  SR: "SUR",
  SE: "SWE",
  CH: "CHE",
  SY: "SYR",
  TJ: "TJK",
  TZ: "TZA",
  TH: "THA",
  TL: "TLS",
  TG: "TGO",
  TO: "TON",
  TT: "TTO",
  TN: "TUN",
  TR: "TUR",
  TM: "TKM",
  TV: "TUV",
  UG: "UGA",
  UA: "UKR",
  AE: "ARE",
  GB: "GBR",
  US: "USA",
  UY: "URY",
  UZ: "UZB",
  VU: "VUT",
  VE: "VEN",
  VN: "VNM",
  YE: "YEM",
  ZM: "ZMB",
  ZW: "ZWE",
  PR: "PRI",
};

/** Retorna o código Alpha-3 seguro a partir de um código Alpha-2 ou texto de nacionalidade */
export function getCountryAlpha3(countryCodeOrName?: string | null): string {
  if (!countryCodeOrName) return "INT";
  const clean = countryCodeOrName.trim().toUpperCase();
  if (clean.length === 3) return clean;
  if (ALPHA2_TO_ALPHA3[clean]) return ALPHA2_TO_ALPHA3[clean];

  // Mapeamentos comuns por nome se veio por extenso
  if (clean.includes("BRAZIL") || clean.includes("BRASIL")) return "BRA";
  if (clean.includes("UNITED STATES") || clean.includes("USA")) return "USA";
  if (clean.includes("CANADA")) return "CAN";
  if (clean.includes("COLOMBIA")) return "COL";
  if (clean.includes("ARGENTINA")) return "ARG";
  if (clean.includes("DOMINICAN")) return "DOM";
  if (clean.includes("PUERTO RICO")) return "PRI";
  if (clean.includes("ITALY") || clean.includes("ITALIA")) return "ITA";
  if (clean.includes("SPAIN") || clean.includes("ESPANHA")) return "ESP";
  if (clean.includes("GERMANY") || clean.includes("ALEMANHA")) return "DEU";

  return clean.slice(0, 3);
}
