/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth.accept-invite'
import { Route as AthleteSlugRouteImport } from './routes/athlete.$slug'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedPortalPipelineRouteImport } from './routes/_authenticated/portal/pipeline'
import { Route as AuthenticatedPortalNotificationsRouteImport } from './routes/_authenticated/portal/notifications'
import { Route as AuthenticatedPortalMediaRouteImport } from './routes/_authenticated/portal/media'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal/documents'
import { Route as AuthenticatedAdminPipelineRouteImport } from './routes/_authenticated/admin/pipeline'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminAthletesIndexRouteImport } from './routes/_authenticated/admin/athletes/index'
import { Route as AuthenticatedAdminAthletesIdRouteImport } from './routes/_authenticated/admin/athletes/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteSlugRoute = AthleteSlugRouteImport.update({
  id: '/athlete/$slug',
  path: '/athlete/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/_authenticated/portal/',
    path: '/portal/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/_authenticated/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalPipelineRoute =
  AuthenticatedPortalPipelineRouteImport.update({
    id: '/_authenticated/portal/pipeline',
    path: '/portal/pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPortalNotificationsRoute =
  AuthenticatedPortalNotificationsRouteImport.update({
    id: '/_authenticated/portal/notifications',
    path: '/portal/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPortalMediaRoute =
  AuthenticatedPortalMediaRouteImport.update({
    id: '/_authenticated/portal/media',
    path: '/portal/media',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/_authenticated/portal/documents',
    path: '/portal/documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminPipelineRoute =
  AuthenticatedAdminPipelineRouteImport.update({
    id: '/_authenticated/admin/pipeline',
    path: '/admin/pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/_authenticated/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/_authenticated/admin/documents',
    path: '/admin/documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAthletesIndexRoute =
  AuthenticatedAdminAthletesIndexRouteImport.update({
    id: '/_authenticated/admin/athletes/',
    path: '/admin/athletes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAthletesIdRoute =
  AuthenticatedAdminAthletesIdRouteImport.update({
    id: '/_authenticated/admin/athletes/$id',
    path: '/admin/athletes/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/athlete/$slug': typeof AthleteSlugRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/media': typeof AuthenticatedPortalMediaRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/pipeline': typeof AuthenticatedPortalPipelineRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/athletes/$id': typeof AuthenticatedAdminAthletesIdRoute
  '/admin/athletes/': typeof AuthenticatedAdminAthletesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/athlete/$slug': typeof AthleteSlugRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/media': typeof AuthenticatedPortalMediaRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/pipeline': typeof AuthenticatedPortalPipelineRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/athletes/$id': typeof AuthenticatedAdminAthletesIdRoute
  '/admin/athletes': typeof AuthenticatedAdminAthletesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/athlete/$slug': typeof AthleteSlugRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/media': typeof AuthenticatedPortalMediaRoute
  '/_authenticated/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/_authenticated/portal/pipeline': typeof AuthenticatedPortalPipelineRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/athletes/$id': typeof AuthenticatedAdminAthletesIdRoute
  '/_authenticated/admin/athletes/': typeof AuthenticatedAdminAthletesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/athlete/$slug'
    | '/auth/accept-invite'
    | '/admin/documents'
    | '/admin/notifications'
    | '/admin/pipeline'
    | '/portal/documents'
    | '/portal/media'
    | '/portal/notifications'
    | '/portal/pipeline'
    | '/admin/'
    | '/portal/'
    | '/admin/athletes/$id'
    | '/admin/athletes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/athlete/$slug'
    | '/auth/accept-invite'
    | '/admin/documents'
    | '/admin/notifications'
    | '/admin/pipeline'
    | '/portal/documents'
    | '/portal/media'
    | '/portal/notifications'
    | '/portal/pipeline'
    | '/admin'
    | '/portal'
    | '/admin/athletes/$id'
    | '/admin/athletes'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/athlete/$slug'
    | '/auth/accept-invite'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/pipeline'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/media'
    | '/_authenticated/portal/notifications'
    | '/_authenticated/portal/pipeline'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/athletes/$id'
    | '/_authenticated/admin/athletes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AthleteSlugRoute: typeof AthleteSlugRoute
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPipelineRoute: typeof AuthenticatedAdminPipelineRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalMediaRoute: typeof AuthenticatedPortalMediaRoute
  AuthenticatedPortalNotificationsRoute: typeof AuthenticatedPortalNotificationsRoute
  AuthenticatedPortalPipelineRoute: typeof AuthenticatedPortalPipelineRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedAdminAthletesIdRoute: typeof AuthenticatedAdminAthletesIdRoute
  AuthenticatedAdminAthletesIndexRoute: typeof AuthenticatedAdminAthletesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/$slug': {
      id: '/athlete/$slug'
      path: '/athlete/$slug'
      fullPath: '/athlete/$slug'
      preLoaderRoute: typeof AthleteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/pipeline': {
      id: '/_authenticated/portal/pipeline'
      path: '/portal/pipeline'
      fullPath: '/portal/pipeline'
      preLoaderRoute: typeof AuthenticatedPortalPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/notifications': {
      id: '/_authenticated/portal/notifications'
      path: '/portal/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof AuthenticatedPortalNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/media': {
      id: '/_authenticated/portal/media'
      path: '/portal/media'
      fullPath: '/portal/media'
      preLoaderRoute: typeof AuthenticatedPortalMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/portal/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/pipeline': {
      id: '/_authenticated/admin/pipeline'
      path: '/admin/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AuthenticatedAdminPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/athletes/': {
      id: '/_authenticated/admin/athletes/'
      path: '/admin/athletes'
      fullPath: '/admin/athletes/'
      preLoaderRoute: typeof AuthenticatedAdminAthletesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/athletes/$id': {
      id: '/_authenticated/admin/athletes/$id'
      path: '/admin/athletes/$id'
      fullPath: '/admin/athletes/$id'
      preLoaderRoute: typeof AuthenticatedAdminAthletesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AthleteSlugRoute: AthleteSlugRoute,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPipelineRoute: AuthenticatedAdminPipelineRoute,
  AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
  AuthenticatedPortalMediaRoute: AuthenticatedPortalMediaRoute,
  AuthenticatedPortalNotificationsRoute: AuthenticatedPortalNotificationsRoute,
  AuthenticatedPortalPipelineRoute: AuthenticatedPortalPipelineRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedAdminAthletesIdRoute: AuthenticatedAdminAthletesIdRoute,
  AuthenticatedAdminAthletesIndexRoute: AuthenticatedAdminAthletesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
