/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalTokenRouteImport } from './routes/proposal.$token'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth.accept-invite'
import { Route as AthleteSlugRouteImport } from './routes/athlete.$slug'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ProposalTokenPdfRouteImport } from './routes/proposal.$token.pdf'
import { Route as AuthenticatedPortalPipelineRouteImport } from './routes/_authenticated/portal/pipeline'
import { Route as AuthenticatedPortalNotificationsRouteImport } from './routes/_authenticated/portal/notifications'
import { Route as AuthenticatedPortalMediaRouteImport } from './routes/_authenticated/portal/media'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal/documents'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminPipelineRouteImport } from './routes/_authenticated/admin/pipeline'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminProposalsIndexRouteImport } from './routes/_authenticated/admin/proposals/index'
import { Route as AuthenticatedAdminAthletesIndexRouteImport } from './routes/_authenticated/admin/athletes/index'
import { Route as AuthenticatedAdminProposalsIdRouteImport } from './routes/_authenticated/admin/proposals/$id'
import { Route as AuthenticatedAdminAthletesIdRouteImport } from './routes/_authenticated/admin/athletes/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalTokenRoute = ProposalTokenRouteImport.update({
  id: '/proposal/$token',
  path: '/proposal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteSlugRoute = AthleteSlugRouteImport.update({
  id: '/athlete/$slug',
  path: '/athlete/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ProposalTokenPdfRoute = ProposalTokenPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => ProposalTokenRoute,
} as any)
const AuthenticatedPortalPipelineRoute =
  AuthenticatedPortalPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalNotificationsRoute =
  AuthenticatedPortalNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalMediaRoute =
  AuthenticatedPortalMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPipelineRoute =
  AuthenticatedAdminPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProposalsIndexRoute =
  AuthenticatedAdminProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAthletesIndexRoute =
  AuthenticatedAdminAthletesIndexRouteImport.update({
    id: '/athletes/',
    path: '/athletes/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProposalsIdRoute =
  AuthenticatedAdminProposalsIdRouteImport.update({
    id: '/proposals/$id',
    path: '/proposals/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAthletesIdRoute =
  AuthenticatedAdminAthletesIdRouteImport.update({
    id: '/athletes/$id',
    path: '/athletes/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/athlete/$slug': typeof AthleteSlugRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/proposal/$token': typeof ProposalTokenRouteWithChildren
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/media': typeof AuthenticatedPortalMediaRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/pipeline': typeof AuthenticatedPortalPipelineRoute
  '/proposal/$token/pdf': typeof ProposalTokenPdfRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/athletes/$id': typeof AuthenticatedAdminAthletesIdRoute
  '/admin/proposals/$id': typeof AuthenticatedAdminProposalsIdRoute
  '/admin/athletes/': typeof AuthenticatedAdminAthletesIndexRoute
  '/admin/proposals/': typeof AuthenticatedAdminProposalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/athlete/$slug': typeof AthleteSlugRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/proposal/$token': typeof ProposalTokenRouteWithChildren
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/media': typeof AuthenticatedPortalMediaRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/pipeline': typeof AuthenticatedPortalPipelineRoute
  '/proposal/$token/pdf': typeof ProposalTokenPdfRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/athletes/$id': typeof AuthenticatedAdminAthletesIdRoute
  '/admin/proposals/$id': typeof AuthenticatedAdminProposalsIdRoute
  '/admin/athletes': typeof AuthenticatedAdminAthletesIndexRoute
  '/admin/proposals': typeof AuthenticatedAdminProposalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/athlete/$slug': typeof AthleteSlugRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/proposal/$token': typeof ProposalTokenRouteWithChildren
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/media': typeof AuthenticatedPortalMediaRoute
  '/_authenticated/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/_authenticated/portal/pipeline': typeof AuthenticatedPortalPipelineRoute
  '/proposal/$token/pdf': typeof ProposalTokenPdfRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/athletes/$id': typeof AuthenticatedAdminAthletesIdRoute
  '/_authenticated/admin/proposals/$id': typeof AuthenticatedAdminProposalsIdRoute
  '/_authenticated/admin/athletes/': typeof AuthenticatedAdminAthletesIndexRoute
  '/_authenticated/admin/proposals/': typeof AuthenticatedAdminProposalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/portal'
    | '/athlete/$slug'
    | '/auth/accept-invite'
    | '/proposal/$token'
    | '/admin/documents'
    | '/admin/notifications'
    | '/admin/pipeline'
    | '/admin/settings'
    | '/portal/documents'
    | '/portal/media'
    | '/portal/notifications'
    | '/portal/pipeline'
    | '/proposal/$token/pdf'
    | '/admin/'
    | '/portal/'
    | '/admin/athletes/$id'
    | '/admin/proposals/$id'
    | '/admin/athletes/'
    | '/admin/proposals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/athlete/$slug'
    | '/auth/accept-invite'
    | '/proposal/$token'
    | '/admin/documents'
    | '/admin/notifications'
    | '/admin/pipeline'
    | '/admin/settings'
    | '/portal/documents'
    | '/portal/media'
    | '/portal/notifications'
    | '/portal/pipeline'
    | '/proposal/$token/pdf'
    | '/admin'
    | '/portal'
    | '/admin/athletes/$id'
    | '/admin/proposals/$id'
    | '/admin/athletes'
    | '/admin/proposals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/athlete/$slug'
    | '/auth/accept-invite'
    | '/proposal/$token'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/pipeline'
    | '/_authenticated/admin/settings'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/media'
    | '/_authenticated/portal/notifications'
    | '/_authenticated/portal/pipeline'
    | '/proposal/$token/pdf'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/athletes/$id'
    | '/_authenticated/admin/proposals/$id'
    | '/_authenticated/admin/athletes/'
    | '/_authenticated/admin/proposals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AthleteSlugRoute: typeof AthleteSlugRoute
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  ProposalTokenRoute: typeof ProposalTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$token': {
      id: '/proposal/$token'
      path: '/proposal/$token'
      fullPath: '/proposal/$token'
      preLoaderRoute: typeof ProposalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/$slug': {
      id: '/athlete/$slug'
      path: '/athlete/$slug'
      fullPath: '/athlete/$slug'
      preLoaderRoute: typeof AthleteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/proposal/$token/pdf': {
      id: '/proposal/$token/pdf'
      path: '/pdf'
      fullPath: '/proposal/$token/pdf'
      preLoaderRoute: typeof ProposalTokenPdfRouteImport
      parentRoute: typeof ProposalTokenRoute
    }
    '/_authenticated/portal/pipeline': {
      id: '/_authenticated/portal/pipeline'
      path: '/pipeline'
      fullPath: '/portal/pipeline'
      preLoaderRoute: typeof AuthenticatedPortalPipelineRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/notifications': {
      id: '/_authenticated/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof AuthenticatedPortalNotificationsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/media': {
      id: '/_authenticated/portal/media'
      path: '/media'
      fullPath: '/portal/media'
      preLoaderRoute: typeof AuthenticatedPortalMediaRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pipeline': {
      id: '/_authenticated/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AuthenticatedAdminPipelineRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/proposals/': {
      id: '/_authenticated/admin/proposals/'
      path: '/proposals'
      fullPath: '/admin/proposals/'
      preLoaderRoute: typeof AuthenticatedAdminProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/athletes/': {
      id: '/_authenticated/admin/athletes/'
      path: '/athletes'
      fullPath: '/admin/athletes/'
      preLoaderRoute: typeof AuthenticatedAdminAthletesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/proposals/$id': {
      id: '/_authenticated/admin/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/admin/proposals/$id'
      preLoaderRoute: typeof AuthenticatedAdminProposalsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/athletes/$id': {
      id: '/_authenticated/admin/athletes/$id'
      path: '/athletes/$id'
      fullPath: '/admin/athletes/$id'
      preLoaderRoute: typeof AuthenticatedAdminAthletesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPipelineRoute: typeof AuthenticatedAdminPipelineRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAthletesIdRoute: typeof AuthenticatedAdminAthletesIdRoute
  AuthenticatedAdminProposalsIdRoute: typeof AuthenticatedAdminProposalsIdRoute
  AuthenticatedAdminAthletesIndexRoute: typeof AuthenticatedAdminAthletesIndexRoute
  AuthenticatedAdminProposalsIndexRoute: typeof AuthenticatedAdminProposalsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminPipelineRoute: AuthenticatedAdminPipelineRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminAthletesIdRoute: AuthenticatedAdminAthletesIdRoute,
    AuthenticatedAdminProposalsIdRoute: AuthenticatedAdminProposalsIdRoute,
    AuthenticatedAdminAthletesIndexRoute: AuthenticatedAdminAthletesIndexRoute,
    AuthenticatedAdminProposalsIndexRoute:
      AuthenticatedAdminProposalsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalMediaRoute: typeof AuthenticatedPortalMediaRoute
  AuthenticatedPortalNotificationsRoute: typeof AuthenticatedPortalNotificationsRoute
  AuthenticatedPortalPipelineRoute: typeof AuthenticatedPortalPipelineRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
    AuthenticatedPortalMediaRoute: AuthenticatedPortalMediaRoute,
    AuthenticatedPortalNotificationsRoute:
      AuthenticatedPortalNotificationsRoute,
    AuthenticatedPortalPipelineRoute: AuthenticatedPortalPipelineRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProposalTokenRouteChildren {
  ProposalTokenPdfRoute: typeof ProposalTokenPdfRoute
}

const ProposalTokenRouteChildren: ProposalTokenRouteChildren = {
  ProposalTokenPdfRoute: ProposalTokenPdfRoute,
}

const ProposalTokenRouteWithChildren = ProposalTokenRoute._addFileChildren(
  ProposalTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AthleteSlugRoute: AthleteSlugRoute,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  ProposalTokenRoute: ProposalTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
